# Generated by Django 4.2.7 on 2026-01-29 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Education",
                "verbose_name_plural": "Educations",
            },
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
    ]
